Add SCTE-35 support
zencoder/go-dash pull request #106
Opened 2024-12-18 22:37 UTC by ferpart

# Description

This pr adds support for SCTE-35 on the go-dash library.

2024-12-18 22:38 UTC, bc-seceng2 commented
![](https://res.cloudinary.com/snyk/image/upload/r-d/scm-platform/snyk-pull-requests/pr-banner-default.svg)

### :tada: **Snyk checks have passed. No issues have been found so far.**

:white_check_mark: **security/snyk** check is complete. No issues have been found. [(View Details)](https://app.snyk.io/org/zencoder/pr-checks/b55e8b36-4959-464b-bc80-f17881e1c803?refs=5d469292d34e5d5c3e8b7372aad055fd3da0084f&source=prChecksComment)

:white_check_mark: **license/snyk** check is complete. No issues have been found. [(View Details)](https://app.snyk.io/org/zencoder/pr-checks/b55e8b36-4959-464b-bc80-f17881e1c803/license?refs=5d469292d34e5d5c3e8b7372aad055fd3da0084f&source=prChecksComment)

2025-01-07 18:23 UTC, mjneil requested changes

2025-01-07 18:23 UTC, mjneil commented on mpd/scte35_test.go
> +	require.EqualString(t, expectedString, actualString)
Rather than test this here, you should have a hardcoded mpd in in the `fixtures/` folder, and compare the `actualString` to the fixture itself much like the event stream tests https://github.com/zencoder/go-dash/blob/master/mpd/events_test.go#L55

The way you have this assertion implemented can actually hide bugs. If there was a bug in say the `xml` tags you added such that the xml encoded value of the struct is invalid, you would never catch it here because both the expected and actual are generated by encoding a struct to xml string, both would encode with the same bug. Comparing against a static fixture can catch any encoding bugs.

2025-01-07 22:07 UTC, ferpart commented on mpd/scte35_test.go
> +	require.EqualString(t, expectedString, actualString)
Updated the test to load the `fixtures/scte35.mpd` file as the expected mpd, and compared it to the generated one here: https://github.com/zencoder/go-dash/pull/106/commits/3754381e7e04cc1d8ff225cf70e406aadf5a73e3

2025-01-07 22:16 UTC, mjneil commented on mpd/fixtures/scte35.mpd
> +          <Binary xmlns="urn:scte:scte35:2014:xml+bin"></Binary>
is it expected to still have a `<Binary></Binary>` tag if there is no data within it, or should we expect this to be omitted? not sure if it is required by the spec or to satisfy precondition requirements?

2025-01-09 20:21 UTC, ferpart commented on mpd/fixtures/scte35.mpd
> +          <Binary xmlns="urn:scte:scte35:2014:xml+bin"></Binary>
Good point, updated the library, to only keep the `Event` field, as that contains the `presentationTime` for an event whenever the binary is empty (also updated a bunch of other stuff to better support scte-35).

2025-01-10 19:01 UTC, mjneil approved these changes

2025-01-13 15:08 UTC, merged